### ISSUE TITLE
Particles is not displayed

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#113]
use /particle flame ~ ~ ~
I didn't see the particle
The official geyser doesn't have this problem
geyser v47 doesn't have this problem

Geyser version: v49

**Comment by Hellohi3654** [comment]
I will look into it

**Comment by Hellohi3654** [comment]
What version are you using (Spigot or Standalone)?

**Comment by zimzaza4** [comment]
> 您正在使用什么版本（Spigot或独立版本）？

Spigot

**Comment by Hellohi3654** [comment]
Thanks

**Comment by Hellohi3654** [comment]
I believe this is a issue with bundabrg's feature/plugins 
So I have created a issue on bunda's fork
(https://github.com/bundabrg/Geyser/issues/8)

**Comment by Hellohi3654** [comment]
No sorry it is a issue with https://github.com/GeyserMC/Geyser/pull/684

**Comment by Hellohi3654** [comment]
not feature/plugins

**Comment by Hellohi3654** [comment]
will fix now

**Comment by Hellohi3654** [comment]
Release v50 should have the fix

**Comment by zimzaza4** [comment]
okay, thank you

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/releases/tag/v51

**Comment by zimzaza4** [comment]
> https://github.com/Hellohi3654/Geyser/releases/tag/v51

![IMG20200926101004](https://user-images.githubusercontent.com/53421735/94327869-89549380-ffe0-11ea-8dbf-9d8c40807edb.jpg)
Skulls has some problems

**Comment by Hellohi3654** [comment]
umm that's weird

**Comment by Hellohi3654** [comment]
never seen that before

**Comment by Hellohi3654** [comment]
the only issue I know of is the player body showing but I've never seen where the body is showing and the head is in the right place

**Comment by Hellohi3654** [comment]
I have reported a similar issue to bunda https://github.com/bundabrg/Geyser/issues/7

**Comment by zimzaza4** [comment]
> 我已经报告了与Bunda [Bundabrg＃7](https://github.com/bundabrg/Geyser/issues/7)类似的问题[](https://github.com/bundabrg/Geyser/issues/7)

Sometimes NPC's skin will become Steve
But the official geyser will not

**Comment by Hellohi3654** [comment]
yeah that's a problem with https://github.com/OnlyBMan/Geyser/tree/custom-skulls
