### ISSUE TITLE
Unable to reload geyser

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#136]
I use geyser-spigot
Unable to reload geyser with /geyser reload
![IMG20201006121826](https://user-images.githubusercontent.com/53421735/95158550-7440e700-07ce-11eb-9b56-bc8460cca9b0.jpg)

**Comment by Hellohi3654** [comment]
yeah I believe that is a problem with https://github.com/GeyserMC/Geyser/pull/1266

**Comment by Hellohi3654** [comment]
I have made a fix in https://github.com/Hellohi3654/Geyser/releases/tag/Bleeding_v67

**Comment by zimzaza4** [comment]
okay, thanks
