### ISSUE TITLE
There's something wrong with the scoreboard

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#143]
When the player enters the server, the content of the scoreboard is not loaded.

If I reload the scoreboard, it will load the contents of the scoreboard.

**Comment by Hellohi3654** [comment]
What version are you using
e.g Bleeding_v68, Bleeding_v69 ?

**Comment by Hellohi3654** [comment]
Also is this an issue on the master branch of Geyser?
Have you tested it there
https://github.com/GeyserMC/Geyser
You can download the latest version from here
https://ci.nukkitx.com/job/GeyserMC/job/Geyser/job/master/

**Comment by zimzaza4** [comment]
Yes. It also has this issue.

**Comment by Hellohi3654** [comment]
Ok 
I would recommend that you create an issue on the official issue tracker
https://github.com/GeyserMC/Geyser/issues
