### ISSUE TITLE
The skin of the skulls and NPC is not loaded

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#159]
Citizens plugin:
![IMG20201026190412](https://user-images.githubusercontent.com/53421735/97165601-ef3e6180-17be-11eb-91eb-770f67eee061.jpg)
Skulls:
![IMG20201026190353](https://user-images.githubusercontent.com/53421735/97165629-f5ccd900-17be-11eb-8197-6b7b385cfe02.jpg)
I also use skin plugins. The player's skin is not loaded either

**Comment by Hellohi3654** [comment]
weird I haven't had this happen to me is this a new issue?

**Comment by Hellohi3654** [comment]
Does this happen with player's?

**Comment by Hellohi3654** [comment]
I will see if I can fix it though

**Comment by Hellohi3654** [comment]
I have tried to fix the issue please let me know if it has worked as I don't really have a way to test

**Comment by zimzaza4** [comment]
> Does this happen with player's?

Yes

**Comment by zimzaza4** [comment]
Bundabrg's Geyser doesn't have this issue... 
Ummm

**Comment by Hellohi3654** [comment]
Have you tried the latest version

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/releases/latest

**Comment by zimzaza4** [comment]
Trying

**Comment by zimzaza4** [comment]
Thank you very much for fixing the issue

**Comment by zimzaza4** [comment]
I use Geyser-bungeerecord now
This problem has not been fixed in geyser-bungeerecord
