### ISSUE TITLE
There seems to be a problem with the player's movement

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#165]
Can't run in the stairs

**Comment by zimzaza4** [comment]
Players will be returned to their original positions

**Comment by Hellohi3654** [comment]
it's snapping the player back

**Comment by Hellohi3654** [comment]
have you got cache-chunks in the config set to true?

**Comment by zimzaza4** [comment]
Yes

> have you got cache-chunks in the config set to true?

**Comment by Hellohi3654** [comment]
try updating to the version I just released https://github.com/Hellohi3654/Geyser/releases/latest

**Comment by Hellohi3654** [comment]
I just tested and can see what you mean I will try and fix this issue

**Comment by Hellohi3654** [comment]
I have fixed this issue in the lastest release
