### ISSUE TITLE
Unable to translate packet: ServerMapDataPacket. Server froze.

### ISSUE THREAD

**Issue by Uboaaaaa** [Hellohi3654/Geyser#166]
**Describe the bug**

A player joins the game through Bedrock edition, the console gets spammed by "null" and "unable to translate packet: ServerMapDataPacket". Alongside with severe TPS drop.

**To Reproduce**

Seems to happens randomly after a player join via bedrock.

**Expected behavior**

Nothing should happen.

**Screenshots / Videos**

https://paste.gg/p/anonymous/e8cfbeb0a9704d758f28c3b22361aad6

**Server Version**

Paper version git-Paper-246 (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)

**Geyser Version**

1.2.0-SNAPSHOT (git-Stable-a9c2875) (Java: 1.16.3, Bedrock: 1.16.0 - 1.16.20)

**Minecraft: Bedrock Edition Version**

1.16.20
**Additional Context**

https://dump.geysermc.org/IXj9DX0k3O3U2JqfRZCvfdvTmx98ciBO

**Comment by Hellohi3654** [comment]
I have never seen this issue before 
On my server I make maps all the time and have never had this issue

**Comment by Hellohi3654** [comment]
This could be because of a map plugin

**Comment by Hellohi3654** [comment]
First try updating to my latest release https://github.com/Hellohi3654/Geyser/releases/latest

**Comment by Uboaaaaa** [comment]
Thanks, will give the lastest release a shot.
Yeah I do have two map plugins running on my server. If the issue still persists I'll try to unistall them and see which one is causing that.

**Comment by Uboaaaaa** [comment]
I have updated to the newest release. The server didn't froze any more.

The issue is possibly caused by an item frame containing an animated picture. Created using the plugin "[G-sign](https://www.spigotmc.org/resources/%E2%9A%A1-gsigns-%E2%9A%A1-a-unique-map-signs-plugin-for-lobbies-1-8-8-1-16-3.73693/)". 

The following error is spammed when I come near an animated item frame. https://paste.gg/p/anonymous/e40f1964e1654ea1a66969deefde9746
The following error is spammed when I come near a non-animated one. https://paste.gg/p/anonymous/3560200193d740148d15e5ec52c5ada0

If you need a translation it's saying something like "`[Geyser-Spigot] Translating data error: entity ITEM_FRAME obtained EntityMetadata(id=7, type=ITEM, value=ItemStack(id=733, amount=1, nbt=CompoundTag { {map=ShortTag(map) { 10001 }} }))`"

Since the plugin doesn't serve an important role I have uninstalled it to ensure people can connect via bedrock. Would be glad to see a compatibility support though.

Thanks for the help!

**Comment by Hellohi3654** [comment]
Hi
Since this is a issue with Geyser itself please make a issue here:
https://github.com/GeyserMC/Geyser/issues

**Comment by Uboaaaaa** [comment]
Hi, Geyser has fixed this issue: https://github.com/GeyserMC/Geyser/pull/1475

**Comment by Hellohi3654** [comment]
Yes just merged the fix
Making a release now
https://github.com/Hellohi3654/Geyser/releases/tag/Bleeding_v91
