### ISSUE TITLE
About trams and ships

### ISSUE THREAD

**Issue by Fedsd1** [Hellohi3654/Geyser#172]
Players can't take trams or boats. The original geyser doesn't have this problem

**Comment by Hellohi3654** [comment]
I will look into a fix when I next update

**Comment by Hellohi3654** [comment]
I believe the problem is caused by heath123's move fixes
I have got the boats to work some what
You have to spam the enter and exit buttons a couple of times then it will allow you to stay sitting in the boat

**Comment by Hellohi3654** [comment]
is this still a issue?

**Comment by Hellohi3654** [comment]
I believe this issue is now fixed
