### ISSUE TITLE
About Mobile fixes

### ISSUE THREAD

**Issue by Fedsd1** [Hellohi3654/Geyser#177]
As shown in the figure, mobile fixes don't seem to work on the latest version of Geyser (V93) and paper server of the latest version, with 1.16.3+ V91 not having this problem

![Video_20201107_091354_853](https://user-images.githubusercontent.com/45486538/98442303-bac39180-213e-11eb-9815-b0778baafe16.gif)

**Comment by Hellohi3654** [comment]
Sorry about that 
Will be fixed on the next release

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/releases/tag/Bleeding_v94
