### ISSUE TITLE
GeyserReversion error

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#233]
Minecraft 1.16.101
GeyserReversionv1.0.28(No problem in older versions)
Players cannot enter the server
![IMG20201210210310](https://user-images.githubusercontent.com/53421735/101775933-2a0c1700-3b2b-11eb-84c9-2f573ac2acf2.jpg)
https://github.com/bundabrg/Geyser
 does not have this error

**Comment by Hellohi3654** [comment]
Could you please test and see if this is an issue with the master branch

**Comment by Hellohi3654** [comment]
Also please test this version
https://github.com/Hellohi3654/Geyser/runs/1533665044?check_suite_focus=true

**Comment by Hellohi3654** [comment]
Please also test: https://github.com/Hellohi3654/Geyser/actions/runs/414066766

**Comment by zimzaza4** [comment]
After testing, they all have the same problem
![IMG20201211062625](https://user-images.githubusercontent.com/53421735/101837303-d2e16300-3b79-11eb-8551-39c14a1bbeff.jpg)

**Comment by zimzaza4** [comment]
> 您能否测试一下，看看这是否与master分支有关



> Could you please test and see if this is an issue with the master branch

How do I download the master branch?

**Comment by Hellohi3654** [comment]
I think bunda needs to update geyserreversion to use bedrock protocol v422 as it is currently on v419

**Comment by Hellohi3654** [comment]
https://github.com/bundabrg/GeyserReversion/issues/25

**Comment by Hellohi3654** [comment]
> I think bunda needs to update geyserreversion to use bedrock protocol v422 as it is currently on v419
 
bundabrg/bleeding branch still works because it has not been updated to v422
which means it doesn't support 1.16.200

**Comment by Hellohi3654** [comment]
> > 您能否测试一下，看看这是否与master分支有关
> 
> > Could you please test and see if this is an issue with the master branch
> 
> How do I download the master branch?

I was just looking at the error didn't realize you were using geyserreversion before

**Comment by zimzaza4** [comment]
> I think bunda needs to update geyserreversion to use bedrock protocol v422 as it is currently on v419

The strange thing is that if I use GeyserReversion v1.0.24 there is no such problem

**Comment by Hellohi3654** [comment]
Umm weird it may because it doesn't support the protocol v422

**Comment by Hellohi3654** [comment]
This should now hopefully be resolved if you update both GeyserReversion and https://github.com/Hellohi3654/Geyser/releases/latest

**Comment by zimzaza4** [comment]
ok
