### ISSUE TITLE
server-inventory?

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#261]
**What feature do you want?**
Add a description
Can you merge this branch?
https://github.com/Camotoy/Geyser/tree/server-inventory

This fixes many inventories

**Comment by Hellohi3654** [comment]
Ok I will have a look

**Comment by Hellohi3654** [comment]
The release I'm about to release will not include the server-inventory branch but the next one after it will include the server-inventory branch

**Comment by Hellohi3654** [comment]
I have created a test branch for the server-inventory branch
You can download artifacts here
https://github.com/Hellohi3654/Geyser/actions/runs/455242409

**Comment by zimzaza4** [comment]
If you take items from the creative mode inventory, the player will be forced to disconnect

**Comment by zimzaza4** [comment]
Ummm...seems to be disconnected after moving an item

**Comment by Hellohi3654** [comment]
yeah there's a few bugs that's why I made a test branch

**Comment by Hellohi3654** [comment]
Here's another build
Might fix some issues
https://github.com/Hellohi3654/Geyser/actions/runs/455578047

**Comment by Hellohi3654** [comment]
Sorry this one if it doesn't fail
https://github.com/Hellohi3654/Geyser/actions/runs/455584212

**Comment by Hellohi3654** [comment]
No sorry again this one should be it
https://github.com/Hellohi3654/Geyser/actions/runs/455586366

**Comment by zimzaza4** [comment]
https://github.com/Hellohi3654/Geyser/actions/runs/455577846
Is it this one?

**Comment by Hellohi3654** [comment]
This one
https://github.com/Hellohi3654/Geyser/actions/runs/455586366

**Comment by zimzaza4** [comment]
Still the same problem...

**Comment by zimzaza4** [comment]
https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/server-inventory/
They don’t seem to build successfully...

**Comment by zimzaza4** [comment]
Players will be disconnected because of CLOSED_BY_REMOTE_PEER

**Comment by Hellohi3654** [comment]
Yeah not sure why 
I think it's because of some `case:`
Also not sure why players are disconnected

Here I fixed the problem causing: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/server-inventory/ not to build

https://github.com/Hellohi3654/Geyser/actions/runs/455616906

**Comment by zimzaza4** [comment]
2021-01-01 12:22:01.406 [Network Listener - #5] I - [0m[1mItemStackRequestPacket(requests=[ItemStackRequestPacket.Request(requestId=-3, actions=[DestroyStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=HOTBAR, slot=7, stackNetworkId=34))])])
 
The information output before the player disconnects

**Comment by zimzaza4** [comment]
> Yeah not sure why
> I think it's because of some `case:`
> Also not sure why players are disconnected
> 
> Here I fixed the problem causing: https://ci.opencollab.dev/job/GeyserMC/job/Geyser/job/server-inventory/ not to build
> 
> https://github.com/Hellohi3654/Geyser/actions/runs/455616906

Wait, I'll try it first

**Comment by Hellohi3654** [comment]
ok

**Comment by Hellohi3654** [comment]
> 2021-01-01 12:22:01.406 [Network Listener - #5] I - �[0m�[1mItemStackRequestPacket(requests=[ItemStackRequestPacket.Request(requestId=-3, actions=[DestroyStackRequestActionData(count=1, source=StackRequestSlotInfoData(container=HOTBAR, slot=7, stackNetworkId=34))])])�
> 
> The information output before the player disconnects

Honestly not sure how to fix that

**Comment by zimzaza4** [comment]
Cannot take items from the creative inventory

**Comment by zimzaza4** [comment]
But those stocks seem to be available

**Comment by zimzaza4** [comment]
There are some minor issues

**Comment by Hellohi3654** [comment]
yeah
smithing tables stonecutters and stuff still don't work

**Comment by zimzaza4** [comment]
I think they will spend a long time on that branch..

**Comment by Hellohi3654** [comment]
Yeah most likely

**Comment by Hellohi3654** [comment]
Here are another two builds
Hellohi3654 version: https://github.com/Hellohi3654/Geyser/actions/runs/456904619

GeyserMC official: https://github.com/Hellohi3654/Geyser/actions/runs/456904940

**Comment by zimzaza4** [comment]
Is it merged https://github.com/GeyserMC/Geyser/tree/server-inventory?

**Comment by Hellohi3654** [comment]
yeah

**Comment by Hellohi3654** [comment]
not into bundabrg-bleeding

**Comment by Hellohi3654** [comment]
there are still alot of issues

**Comment by Hellohi3654** [comment]
Here's another update to my version:
https://github.com/Hellohi3654/Geyser/actions/runs/456983495

**Comment by Hellohi3654** [comment]
Update to my version again
Crafting tables should work:
https://github.com/Hellohi3654/Geyser/actions/runs/457384913

**Comment by dudebehinddude** [comment]
crafting works client-side but not server side

**Comment by zimzaza4** [comment]
They updated this branch at https://github.com/Camotoy/Geyser/tree/server-inventory

**Comment by Hellohi3654** [comment]
ok I'll update my branch

**Comment by Hellohi3654** [comment]
Update:
https://github.com/Hellohi3654/Geyser/actions/runs/474965543

**Comment by Hellohi3654** [comment]
nevermind seems to crash on startup

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/actions/runs/474982674

**Comment by zimzaza4** [comment]
> https://github.com/Hellohi3654/Geyser/actions/runs/474982674

Player cannot speak

**Comment by Hellohi3654** [comment]
?

**Comment by zimzaza4** [comment]
Well, it seems to be a small chance problem

**Comment by Hellohi3654** [comment]
weird

**Comment by Hellohi3654** [comment]
hang on I'm compiling another build

**Comment by zimzaza4** [comment]
Player inventory is still problematic...

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/actions/runs/475005374

**Comment by Hellohi3654** [comment]
yeah

**Comment by Hellohi3654** [comment]
try that one ^

**Comment by zimzaza4** [comment]
![IMG20210110112753](https://user-images.githubusercontent.com/53421735/104113713-1117a100-5337-11eb-899d-faf425045ebb.jpg)
I dropped the item

**Comment by zimzaza4** [comment]
But the items in the inventory have not changed
![IMG20210110112806](https://user-images.githubusercontent.com/53421735/104113720-2ab8e880-5337-11eb-86b6-1fe64a55599c.jpg)

**Comment by Hellohi3654** [comment]
I don't think they've added that yet

**Comment by zimzaza4** [comment]
> https://github.com/Hellohi3654/Geyser/actions/runs/475005374

Ok i'll try

**Comment by Hellohi3654** [comment]
once it's done

**Comment by Hellohi3654** [comment]
that bug you mentioned before seems to be gone

**Comment by Hellohi3654** [comment]
crafting works

**Comment by zimzaza4** [comment]
> that bug you mentioned before seems to be gone

Did not disappear

**Comment by zimzaza4** [comment]
I changed the position of the item in the inventory

**Comment by zimzaza4** [comment]
But there is no change in the shortcut bar

**Comment by Hellohi3654** [comment]
weird i'm not having the same problems

**Comment by Hellohi3654** [comment]
Are you using this version?
https://github.com/Hellohi3654/Geyser/actions/runs/475005374

**Comment by zimzaza4** [comment]
Have you also tested it?  Can I go to your test server to test?

**Comment by zimzaza4** [comment]
> Are you using this version?
> https://github.com/Hellohi3654/Geyser/actions/runs/475005374

yes

**Comment by Hellohi3654** [comment]
My test server is 
IP: 54.253.235.141
Port: 19132

**Comment by Hellohi3654** [comment]
If you want to join

**Comment by zimzaza4** [comment]
Yes it's weird...

**Comment by zimzaza4** [comment]
Do you also use GeyserReversion?

**Comment by zimzaza4** [comment]
I think this may be related to it

**Comment by zimzaza4** [comment]
It is indeed its problem

**Comment by zimzaza4** [comment]
When command completion is turned on

Sending / will cause the client to freeze

There is no such problem in your default branch

**Comment by Hellohi3654** [comment]
Yeah GeyserReversion probably effects things

I did notice that when I was testing 
Not sure why that happens
I'll look into it

**Comment by zimzaza4** [comment]
Anvil cannot be used

**Comment by Hellohi3654** [comment]
I'm sure they'll fix it soon

**Comment by Hellohi3654** [comment]
can't figure out why it freezes when using /

**Comment by Hellohi3654** [comment]
i'll do a file comparsion tommorrow it's 30 mins until 1 am

**Comment by zimzaza4** [comment]
His branch is updated, maybe the anvil is fixed

**Comment by Hellohi3654** [comment]
Thank you for the heads up

Updated to Geyser Master

I will now update to his branch

https://github.com/Hellohi3654/Geyser/actions/runs/480173990

**Comment by Hellohi3654** [comment]
ok here's another update
merged camotoy's branch

https://github.com/Hellohi3654/Geyser/actions/runs/480328708

**Comment by Hellohi3654** [comment]
they have to be releasing a test branch soon

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/actions/runs/482118091

**Comment by zimzaza4** [comment]
After testing, the anvil has been repaired

**Comment by zimzaza4** [comment]
Same for Cartography Table

**Comment by zimzaza4** [comment]
All inventory is fixed

**Comment by zimzaza4** [comment]
But there seems to be a problem

**Comment by zimzaza4** [comment]
Seems a bit stuck...

**Comment by Hellohi3654** [comment]
?

**Comment by Hellohi3654** [comment]
I have noticed one other thing
 You can't rename things in the anvil

**Comment by zimzaza4** [comment]
Chunks loading is slower

**Comment by zimzaza4** [comment]
If there is no bookshelf beside the enchanting table, the enchantment may not be displayed

**Comment by zimzaza4** [comment]
Ummm... I think this issue can be closed

**Comment by Hellohi3654** [comment]
Hmm strange 
It might all be fixed when it is official
