### ISSUE TITLE
pistons

### ISSUE THREAD

**Issue by dudebehinddude** [Hellohi3654/Geyser#287]
**Describe the bug**

pistons are very buggy, and flying machines will create ghost blocks

**To Reproduce**

literally power a piston, and it looks very odd
or
1. create a flying machine
2. power it
ghost blocks

**Expected behavior**

pistons to look normal

**Screenshots / Videos**

**Server Version and Plugins**

i was doing this on inventory-final, but should still be there on the normal version

**Geyser Dump**

https://dump.geysermc.org/kAe0KNZ2nLuvwT1Yq2rD1Dh0zU5KqWTj

**Minecraft: Bedrock Edition Version**

1.16.201 (win 10)

**Additional Context**

**Comment by dudebehinddude** [comment]
i would guess that this has to do with the smooth pistons pr; any way to disable it? (i'd assume not, but may as well ask)

**Comment by Hellohi3654** [comment]
If are you using the server-inventory-final branch
please try using the bundabrg-bleeding branch to see if it is still an issue

**Comment by dudebehinddude** [comment]
the issue still exists on v159

**Comment by dudebehinddude** [comment]
of blundabrg-bleeding

**Comment by Hellohi3654** [comment]
This maybe a issue related to the problem where if too many blocks are world edited out there are Ghost blocks

**Comment by Hellohi3654** [comment]
How often do Ghost blocks appear?

**Comment by dudebehinddude** [comment]
On every cycle of a flying machine

**Comment by dudebehinddude** [comment]
I can attach a video tmr if u want

**Comment by Hellohi3654** [comment]
That would be great thanks

**Comment by dudebehinddude** [comment]
a

https://user-images.githubusercontent.com/66212375/104948092-bb707380-598a-11eb-8d81-8ddfff2bb014.mp4

**Comment by Hellohi3654** [comment]
oh I see

**Comment by Hellohi3654** [comment]
thanks for the video

**Comment by Hellohi3654** [comment]
hopefully the latest release will fix pistons

**Comment by Hellohi3654** [comment]
https://gyazo.com/2853ddcd16bfa1d42861aea95b39dc09

**Comment by Hellohi3654** [comment]
no longer creates ghost blocks but blocks go white

**Comment by dudebehinddude** [comment]
Nice so should I close?

**Comment by Hellohi3654** [comment]
Nah leave it open so the issue reminds me that I need to fix the blocks going white

**Comment by dudebehinddude** [comment]
okay

**Comment by dudebehinddude** [comment]
do you mind if i merge your fix-piston branch into my fork? or was it a more updated version of the smooth piston pr

**Comment by Hellohi3654** [comment]
No that's fine
I think the pistonfix branch is up to date

**Comment by Hellohi3654** [comment]
my latest release v161 should have hopefully fixed all issues with pistons
https://github.com/Hellohi3654/Geyser/releases/tag/Bleeding_v161

**Comment by Hellohi3654** [comment]
also there's a new branch called fixpistons which is up to date with the smooth pistons PR
https://github.com/Hellohi3654/Geyser/tree/fixpistons

**Comment by dudebehinddude** [comment]
Does that include the fixes you made to pistons or just the pr

**Comment by Hellohi3654** [comment]
Umm no just the PR 
I never made any fixes I just remerged as another PR may of changed some core code of the smooth pistons PR
Making it break

**Comment by Hellohi3654** [comment]
Anyway I'm going to close this issue as I think everythings fixed
