### ISSUE TITLE
need floodgate 2.0

### ISSUE THREAD

**Issue by RhythmNz** [Hellohi3654/Geyser#291]
**What feature do you want?**
Add a description

**Alternatives?**
List any alternatives you might have tried

**Comment by Hellohi3654** [comment]
What are the benefits of floodgate 2.0?

**Comment by zimzaza4** [comment]
> What are the benefits of floodgate 2.0?

Added form. 
Player skins can be converted to Bedrock Edition.

**Comment by zimzaza4** [comment]
Floodgate 2.0
https://github.com/Tim203/Floodgate
Floodgate2.0 Geyser
https://github.com/Tim203/Geyser

**Comment by zimzaza4** [comment]
API...? 
https://github.com/GeyserMC/Cumulus

**Comment by zimzaza4** [comment]
https://github.com/GeyserMC/Floodgate/wiki/Forms
Forms

**Comment by Hellohi3654** [comment]
Is it stable?
and does everything work?

**Comment by RhythmNz** [comment]
> Is it stable?
> and does everything work?

yep erverthing work

**Comment by Hellohi3654** [comment]
I might create a new branch dedicated to floodgate 2.0 like I did with inventory fixes

**Comment by RhythmNz** [comment]
> I might create a new branch dedicated to floodgate 2.0 like I did with inventory fixes

i hope can have floodgate2.0 with  inventory fixes

**Comment by Hellohi3654** [comment]
umm I mean I can try

**Comment by RhythmNz** [comment]
> umm I mean I can try

thank so much

**Comment by Hellohi3654** [comment]
ok gonna start work on floodgate 2.0 branch

**Comment by Hellohi3654** [comment]
First successful build of floodgate 2.0 branch
https://github.com/Hellohi3654/Geyser/actions/runs/516707512

**Comment by Hellohi3654** [comment]
You can check releases for newer versions
https://github.com/Hellohi3654/Geyser/releases

**Comment by Hellohi3654** [comment]
do you guys know where to get a floodgate 2.0.jar?

**Comment by Hellohi3654** [comment]
if you want floodgate 2.0 
You can find it here https://github.com/Hellohi3654/Floodgate/releases

**Comment by dudebehinddude** [comment]
uh oh
https://pastebin.com/e71vJuM3

Using floodgate2.0 v8 and geyser floodgate 2.0 v178

**Comment by dudebehinddude** [comment]
Disabling player linking in the config fixes it, so I'm guessing that's not done yet in floodgate 2.0

**Comment by Hellohi3654** [comment]
Yeah sounds like that maybe the solution
If you have any issues please create another issue as this issue only requested floodgate
