### ISSUE TITLE
Server-Inventory Bug

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#298]
The player cannot place any blocks. 
Cannot interact with entities (NPCs)

**Comment by zimzaza4** [comment]
I am using
https://github.com/Hellohi3654/Geyser/actions/runs/507374974

**Comment by zimzaza4** [comment]
No problems in this version
https://github.com/Hellohi3654/Geyser/actions/runs/507205735

**Comment by Hellohi3654** [comment]
is this still an issue in this build?
https://github.com/Hellohi3654/Geyser/releases/tag/Serverinventory_v168

**Comment by Hellohi3654** [comment]
I just tested that build and everything seems to be working fine

**Comment by zimzaza4** [comment]
Okay, but the player cannot use /geyser offhand

**Comment by Hellohi3654** [comment]
yeah I believe that hasn't been implemented yet

**Comment by zimzaza4** [comment]
But it can be used in older versions(server-inventory-final)

**Comment by zimzaza4** [comment]
I used https://github.com/Hellohi3654/Geyser/releases/tag/Serverinventory_v174

**Comment by zimzaza4** [comment]
The problem still exists.

**Comment by zimzaza4** [comment]
My server version is 1.16.4

**Comment by zimzaza4** [comment]
But V168 is very stable without too many problems

**Comment by Hellohi3654** [comment]
I'm currently using v168 and I am able to use Geyser offhand
Also players are able to interact with NPC's and place blocks
Also v174 only Updates to master and a few smooth pistons changes so I don't see why anything to do with server-inventory would of changed
