### ISSUE TITLE
Weird mapping error

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#319]
There will be some mapping problems in pistons, arrows, snowballs, etc.
I use Geyser-Spigot (server-inventory)
![IMG20210217131246](https://user-images.githubusercontent.com/53421735/108159392-e123a080-7121-11eb-9a31-2507d4d245b6.jpg)
Projectiles such as snowballs will have a stutter problem

**Comment by Hellohi3654** [comment]
hmm

**Comment by Hellohi3654** [comment]
I'll try remerging my mapping fork and updating submodules

**Comment by Hellohi3654** [comment]
also which server-inventory branch do you use?

**Comment by zimzaza4** [comment]
> also which server-inventory branch do you use?

![IMG20210217183545](https://user-images.githubusercontent.com/53421735/108192244-ffec5c00-714e-11eb-9e5e-be601a487f70.jpg)

**Comment by Hellohi3654** [comment]
ok thanks

**Comment by Hellohi3654** [comment]
fixed
