### ISSUE TITLE
Command completion problem

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#328]
Java: Tuinity 1.16.5
Bedrock: server-inventory
The description of all commands has become like this

![IMG20210220191727](https://user-images.githubusercontent.com/53421735/108593708-4b517500-73b0-11eb-8f67-bd195c87fe5e.jpg)

**Comment by Hellohi3654** [comment]
Oh

**Comment by Hellohi3654** [comment]
Is it still like that?

**Comment by zimzaza4** [comment]
Yes, but it seems to be a problem with the master branch
