### ISSUE TITLE
Firework particles have no color

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#339]
Server-Inventoty

**Describe the bug**
Firework particles have no color
**To Reproduce**
Produce colorful firework particles
The particles of fireworks are white

**Expected behavior**
Firework particles should have color
**Screenshots**

**Device:**
 - Device: [e.g. iPhone, Win 10, Android]
Android
**Additional context**
I don’t know if this is an official branch issue

**Comment by Hellohi3654** [comment]
Unfortunately due to a problem I cannot work on any of my branches because of a dependency problem

Thanks for the issue I will have a look once I can build my branches again

**Comment by zimzaza4** [comment]
Okay thank you

**Comment by zimzaza4** [comment]
Okay thank you

**Comment by zimzaza4** [comment]
Sorry, this seems to be a problem with my plugin
