### ISSUE TITLE
Falied to encrypt message

### ISSUE THREAD

**Issue by Hoangviphb999** [Hellohi3654/Geyser#345]
Minecraft Version: 1.8.8
Server's software: Paper/Spigot
Error type: Failed to encrypt message
Error code: https://pastebin.com/gZRcEZLx

**Comment by Hellohi3654** [comment]
What branch are you using?

**Comment by Hoangviphb999** [comment]
Im using Bleeding Branch v26

**Comment by Hoangviphb999** [comment]
And the lateset Branch can't connect to server

**Comment by Hellohi3654** [comment]
Please try the latest version https://github.com/Hellohi3654/Geyser/releases/tag/New-Bleeding_v28

**Comment by Hoangviphb999** [comment]
> Please try the latest version https://github.com/Hellohi3654/Geyser/releases/tag/New-Bleeding_v28

Thanks, the bug is fixed, now i need to wait GeyserReversion Release

**Comment by Hellohi3654** [comment]
just a warning GeyserReversion might break the server-inventory part of that branch
