### ISSUE TITLE
Floodgate2.0

### ISSUE THREAD

**Issue by zimzaza4** [Hellohi3654/Geyser#346]
I used your Floodgate2.0 and Geyser-floodgate 2.0
Players cannot enter the server
![IMG20210311183639](https://user-images.githubusercontent.com/53421735/110774429-c19f1400-8298-11eb-8105-9cf4616e83ed.jpg)

**Comment by Hellohi3654** [comment]
Unfortunately I don't haven't had time lately to update the floodgate branch

**Comment by Hellohi3654** [comment]
Finally got time to update the floodgate branch

Haven't tested it but I completely remerged so it should of fixed the issue

https://github.com/Hellohi3654/Geyser/releases/tag/New-Floodgate2.0_v33

**Comment by zimzaza4** [comment]
![IMG20210320191130](https://user-images.githubusercontent.com/53421735/111867691-a75be900-89b0-11eb-9c3b-7b57c0ceaa4c.jpg)

**Comment by Hellohi3654** [comment]
I might need to update

**Comment by Hellohi3654** [comment]
what version of floodgate are you using?

**Comment by zimzaza4** [comment]
https://github.com/Hellohi3654/Floodgate/releases/tag/Floodgate2.0_v16

**Comment by Hellohi3654** [comment]
please use the latest release https://github.com/Hellohi3654/Geyser/releases/tag/New-Floodgate2.0_v33

**Comment by Hellohi3654** [comment]
and see if the problem persists

**Comment by zimzaza4** [comment]
![IMG20210324204353](https://user-images.githubusercontent.com/53421735/112312456-caa0d400-8ce1-11eb-9ede-0b76e4bff442.jpg)

[floodgate] Expected 12 arguments.  got 13. Is Geyser up-to-date?

**Comment by Hellohi3654** [comment]
Yeah I think I need to update my branch

**Comment by Hellohi3654** [comment]
There's been a update since I sent my last message

**Comment by Hellohi3654** [comment]
updating now

**Comment by Hellohi3654** [comment]
also make sure you are using the latest version of floodgate 2.0 from here
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.0/

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/releases/tag/New-Floodgate2.0_v35

Here's my new build hopefully that build of floodgate above and this build should work

**Comment by zimzaza4** [comment]
![IMG20210327074155](https://user-images.githubusercontent.com/53421735/112702916-11542100-8ed0-11eb-84d6-1b8b44fa30a1.jpg)

**Comment by zimzaza4** [comment]
Connection closed.

**Comment by Hellohi3654** [comment]
what are you running floodgate on?

**Comment by zimzaza4** [comment]
https://ci.opencollab.dev/job/GeyserMC/job/Floodgate/job/dev%252F2.0/

**Comment by Hellohi3654** [comment]
![image](https://user-images.githubusercontent.com/57390764/112703254-5422f280-8eea-11eb-8c79-5d2148b51933.png)

**Comment by Hellohi3654** [comment]
try using all of them

**Comment by zimzaza4** [comment]
Put it in the plugins folder?

**Comment by Hellohi3654** [comment]
yeah

**Comment by zimzaza4** [comment]
Only floodgate-spigot is loaded

**Comment by zimzaza4** [comment]
Umm.. Should I update Geyser?

**Comment by Hellohi3654** [comment]
yeah

**Comment by Hellohi3654** [comment]
https://github.com/Hellohi3654/Geyser/releases/tag/New-Floodgate2.0_v35

**Comment by zimzaza4** [comment]
It succeeded, thanks for your help! 👍
