### ISSUE TITLE
Does this branch version still support extensions?

### ISSUE THREAD

**Issue by ghost** [Hellohi3654/Geyser#375]
### What feature do you want to see added?

Does this branch version still support extensions?
If not, I hope to add, thanks

### Are there any alternatives?

none

**Comment by Hellohi3654** [comment]
No it no longer supports extensions
I don't really do much with geyser anymore
At the moment my main branch is basically the same as geyser master 

I might start merging other branches again

**Comment by ShredRum** [comment]
I want to use the GeyserLogin extension, but the compatible version of Geyser does not support 1.17.1.  What can I do in this case?

**Comment by ghost** [comment]
> I want to use the GeyserLogin extension, but the compatible version of Geyser does not support 1.17.1. What can I do in this case?

merge bundabrg's geyser fork with the official latest fork by yourself :P

**Comment by ShredRum** [comment]
> > I want to use the GeyserLogin extension, but the compatible version of Geyser does not support 1.17.1. What can I do in this case?
> 
> merge bundabrg's geyser fork with the official latest fork by yourself :P

Thanks for the answer, but I have never used git and am not good at merging branches.  I tried to do this via github and got the error "cannot automatically merge branches."  can you please tell me which branches should be merged with, and which should be in the base, and which should be in the head?  Thanks.  If possible, take a screenshot).  Sorry for the mistakes, I am using a translator.

**Comment by Hellohi3654** [comment]
> > > I want to use the GeyserLogin extension, but the compatible version of Geyser does not support 1.17.1. What can I do in this case?
> > 
> > 
> > merge bundabrg's geyser fork with the official latest fork by yourself :P
> 
> Thanks for the answer, but I have never used git and am not good at merging branches. I tried to do this via github and got the error "cannot automatically merge branches." can you please tell me which branches should be merged with, and which should be in the base, and which should be in the head? Thanks. If possible, take a screenshot). Sorry for the mistakes, I am using a translator.

I would recommend getting github desktop and using that to merge branches
I would recommend forking the master branch and merging bundabrg's bleeding into that
You could also try forking bundabrg's bleeding branch and merging the master branch into that it might be easier

I would recommend using github desktop to perform merges
Just create a pull request and click open with github desktop
It makes it much easier to merge branches because it tells you exactly what files have conflicts

**Comment by Hellohi3654** [comment]
Just tried merged bundabrg's plugin branch into the master branch
Bundabrg's branch is extremely outdated and I doubt any of his plugins will still work in the latest version

If you still want to merge it feel free to continue troubleshooting the compile errors here:
https://github.com/Hellohi3654/Geyser/tree/extensions-main
https://github.com/Hellohi3654/Geyser/runs/4031605306

Some dependencies used by Bundabrg have been removed from Geyser or need updating

I don't think it's worth merging the plugin branch (which is extensions)

**Comment by ghost** [comment]
> > > I want to use the GeyserLogin extension, but the compatible version of Geyser does not support 1.17.1. What can I do in this case?
> > 
> > 
> > merge bundabrg's geyser fork with the official latest fork by yourself :P
> 
> Thanks for the answer, but I have never used git and am not good at merging branches. I tried to do this via github and got the error "cannot automatically merge branches." can you please tell me which branches should be merged with, and which should be in the base, and which should be in the head? Thanks. If possible, take a screenshot). Sorry for the mistakes, I am using a translator.

bundabrg updated his fork (although isn't himself), you can try it
